net stop „Windows Update”
net stop „SysmMain"
net stop „Faks" 
net stop „Usługa udostępniania portów Net.Tcp"
net stop „Foldery robocze"
net stop „Tożsamość aplikacji"
net stop „Usługa lokalizacyjna"
net stop "Usługa wymiany danych funkcji Hyper-V"
net stop "Usługa pulsu funkcji Hyper-V"
net stop "Usługa sieciowa Xbox Live"
net stop "Usługa synchronizacji czasu funkcji Hyper-V"
net stop "Usługa wymiany danych funkcji Hyper-V"
net stop "Usługa wirtualizacji pulpitu zdalnego funkcji Hyper-V"
net stop "Usługa monitorowania czujników"
net stop "Usługa danych czujników"
net stop "Usługa czujników"
net stop "Środowiska i telemetria połączonego użytkownika"
net stop "Udostępnianie połączenia internetowego (ICS)"
net stop "Usługa sieciowa Xbox Live"
net stop "Usługa biometryczna systemu Windows"
net stop "Klient śledzenia linków rozproszonych"
net stop "Usługa raportowania błędów systemu Windows"
net stop "Rejestr zdalny"
